# examen-1b-freire-alex

# 2

In [4]:
import numpy as np

In [6]:
np.zeros((10))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# 3

In [11]:
b=np.zeros((10))

In [12]:
b[5]=1

In [13]:
b

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

# 4

In [9]:
a=np.arange((50))

In [10]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [12]:
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

# 5

In [9]:
np.arange((9)).reshape(1,3,3)

array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])

# 6

In [14]:
arreglo=[1,2,0,0,4,0]

In [16]:
for elemento in arreglo:
    if elemento != 0:
        print(f"indice: {arreglo.index(elemento)}")

indice: 0
indice: 1
indice: 4


# 7

In [18]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# 8

In [22]:
np.random.random((3,3,3))

array([[[0.07275231, 0.69967573, 0.79175486],
        [0.56398613, 0.73304044, 0.3287647 ],
        [0.35525285, 0.61876937, 0.77954519]],

       [[0.06926685, 0.85092223, 0.6077218 ],
        [0.41597545, 0.59137683, 0.58533853],
        [0.26490519, 0.56320206, 0.45204265]],

       [[0.7385294 , 0.16354243, 0.11881454],
        [0.91996774, 0.18771322, 0.99131203],
        [0.32502391, 0.0673809 , 0.85140765]]])

# 9

In [27]:
d=np.random.random((10,10))

In [28]:
d

array([[0.10393491, 0.04708212, 0.42384448, 0.15918893, 0.25052629,
        0.03807538, 0.65896047, 0.52593366, 0.64827076, 0.70173537],
       [0.44299659, 0.08391342, 0.09930273, 0.76005049, 0.94588895,
        0.94334996, 0.78684544, 0.28019393, 0.91421445, 0.0472033 ],
       [0.67487221, 0.62076284, 0.54681724, 0.23764571, 0.41003359,
        0.82884474, 0.55417204, 0.81974044, 0.27568835, 0.57401394],
       [0.61297817, 0.51409916, 0.53933847, 0.0584554 , 0.6814824 ,
        0.93635242, 0.248627  , 0.81202034, 0.49472827, 0.51007667],
       [0.98684927, 0.20707789, 0.0322784 , 0.416914  , 0.87606682,
        0.18799983, 0.65526746, 0.27984958, 0.76610325, 0.95374494],
       [0.11047362, 0.94805409, 0.77071455, 0.8865555 , 0.98431524,
        0.30153726, 0.57535698, 0.47379028, 0.20958835, 0.28463085],
       [0.40140993, 0.14786222, 0.54601433, 0.78714649, 0.16810464,
        0.77472418, 0.94460252, 0.34866921, 0.89523914, 0.73848493],
       [0.89849567, 0.78612555, 0.1673927