# examen-1b-freire-alex

# 2

In [4]:
import numpy as np
from scipy import ndimage
from scipy import misc

In [6]:
np.zeros((10))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# 3

In [11]:
b=np.zeros((10))

In [12]:
b[5]=1

In [13]:
b

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

# 4

In [9]:
a=np.arange((50))

In [10]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [12]:
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

# 5

In [9]:
np.arange((9)).reshape(1,3,3)

array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])

# 6

In [14]:
arreglo=[1,2,0,0,4,0]

In [16]:
for elemento in arreglo:
    if elemento != 0:
        print(f"indice: {arreglo.index(elemento)}")

indice: 0
indice: 1
indice: 4


# 7

In [18]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# 8

In [22]:
np.random.random((3,3,3))

array([[[0.07275231, 0.69967573, 0.79175486],
        [0.56398613, 0.73304044, 0.3287647 ],
        [0.35525285, 0.61876937, 0.77954519]],

       [[0.06926685, 0.85092223, 0.6077218 ],
        [0.41597545, 0.59137683, 0.58533853],
        [0.26490519, 0.56320206, 0.45204265]],

       [[0.7385294 , 0.16354243, 0.11881454],
        [0.91996774, 0.18771322, 0.99131203],
        [0.32502391, 0.0673809 , 0.85140765]]])

# 9

In [27]:
d=np.random.random((10,10))

In [28]:
d

array([[0.10393491, 0.04708212, 0.42384448, 0.15918893, 0.25052629,
        0.03807538, 0.65896047, 0.52593366, 0.64827076, 0.70173537],
       [0.44299659, 0.08391342, 0.09930273, 0.76005049, 0.94588895,
        0.94334996, 0.78684544, 0.28019393, 0.91421445, 0.0472033 ],
       [0.67487221, 0.62076284, 0.54681724, 0.23764571, 0.41003359,
        0.82884474, 0.55417204, 0.81974044, 0.27568835, 0.57401394],
       [0.61297817, 0.51409916, 0.53933847, 0.0584554 , 0.6814824 ,
        0.93635242, 0.248627  , 0.81202034, 0.49472827, 0.51007667],
       [0.98684927, 0.20707789, 0.0322784 , 0.416914  , 0.87606682,
        0.18799983, 0.65526746, 0.27984958, 0.76610325, 0.95374494],
       [0.11047362, 0.94805409, 0.77071455, 0.8865555 , 0.98431524,
        0.30153726, 0.57535698, 0.47379028, 0.20958835, 0.28463085],
       [0.40140993, 0.14786222, 0.54601433, 0.78714649, 0.16810464,
        0.77472418, 0.94460252, 0.34866921, 0.89523914, 0.73848493],
       [0.89849567, 0.78612555, 0.1673927

In [32]:
print(f"valor maximo:{max(item[2] for item in d)}")

valor maximo:0.9866764592420881


In [33]:
print(f"valor minimo:{min(item[2] for item in d)}")

valor minimo:0.03227839528908216


# 10

In [35]:
get_spaced_colors(5)

[(0, 0, 0), (50, 154, 51), (101, 52, 102), (151, 206, 153), (202, 104, 204)]

In [39]:
mapache=misc.face()

In [40]:
mapache

array([[[121, 112, 131],
        [138, 129, 148],
        [153, 144, 165],
        ...,
        [119, 126,  74],
        [131, 136,  82],
        [139, 144,  90]],

       [[ 89,  82, 100],
        [110, 103, 121],
        [130, 122, 143],
        ...,
        [118, 125,  71],
        [134, 141,  87],
        [146, 153,  99]],

       [[ 73,  66,  84],
        [ 94,  87, 105],
        [115, 108, 126],
        ...,
        [117, 126,  71],
        [133, 142,  87],
        [144, 153,  98]],

       ...,

       [[ 87, 106,  76],
        [ 94, 110,  81],
        [107, 124,  92],
        ...,
        [120, 158,  97],
        [119, 157,  96],
        [119, 158,  95]],

       [[ 85, 101,  72],
        [ 95, 111,  82],
        [112, 127,  96],
        ...,
        [121, 157,  96],
        [120, 156,  94],
        [120, 156,  94]],

       [[ 85, 101,  74],
        [ 97, 113,  84],
        [111, 126,  97],
        ...,
        [120, 156,  95],
        [119, 155,  93],
        [118, 154,  92]]

In [51]:
def get_different_colors(n):
    max_value = 16581375 
    interval = int(max_value / n)
    colors = [hex(I)[2:].zfill(6) for I in range(0, max_value, interval)]
    
    return [(int(i[:2], 16), int(i[2:4], 16), int(i[4:], 16)) for i in colors]

In [44]:
len(mapache)

768

In [52]:
get_different_colors(len(mapache))

[(0, 0, 0),
 (0, 84, 86),
 (0, 168, 172),
 (0, 253, 2),
 (1, 81, 88),
 (1, 165, 174),
 (1, 250, 4),
 (2, 78, 90),
 (2, 162, 176),
 (2, 247, 6),
 (3, 75, 92),
 (3, 159, 178),
 (3, 244, 8),
 (4, 72, 94),
 (4, 156, 180),
 (4, 241, 10),
 (5, 69, 96),
 (5, 153, 182),
 (5, 238, 12),
 (6, 66, 98),
 (6, 150, 184),
 (6, 235, 14),
 (7, 63, 100),
 (7, 147, 186),
 (7, 232, 16),
 (8, 60, 102),
 (8, 144, 188),
 (8, 229, 18),
 (9, 57, 104),
 (9, 141, 190),
 (9, 226, 20),
 (10, 54, 106),
 (10, 138, 192),
 (10, 223, 22),
 (11, 51, 108),
 (11, 135, 194),
 (11, 220, 24),
 (12, 48, 110),
 (12, 132, 196),
 (12, 217, 26),
 (13, 45, 112),
 (13, 129, 198),
 (13, 214, 28),
 (14, 42, 114),
 (14, 126, 200),
 (14, 211, 30),
 (15, 39, 116),
 (15, 123, 202),
 (15, 208, 32),
 (16, 36, 118),
 (16, 120, 204),
 (16, 205, 34),
 (17, 33, 120),
 (17, 117, 206),
 (17, 202, 36),
 (18, 30, 122),
 (18, 114, 208),
 (18, 199, 38),
 (19, 27, 124),
 (19, 111, 210),
 (19, 196, 40),
 (20, 24, 126),
 (20, 108, 212),
 (20, 193, 42),


# 11

In [6]:
import pandas as pd
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

In [54]:
mylist

['a',
 'b',
 'c',
 'e',
 'd',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z']

In [57]:
mm=pd.Series(v[0] for v in mylist)

In [61]:
print(f"list to series\n{mm}")

list to series
0     a
1     b
2     c
3     e
4     d
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object


In [65]:
myarr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25])

In [68]:
mn=pd.Series(myarr)

In [69]:
print(f"array to series\n{mn}")

array to series
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
17    17
18    18
19    19
20    20
21    21
22    22
23    23
24    24
25    25
dtype: int32


In [70]:
print(f"diccionario to series\n{pd.Series(mydict)}")

diccionario to series
a     0
b     1
c     2
e     3
d     4
f     5
g     6
h     7
i     8
j     9
k    10
l    11
m    12
n    13
o    14
p    15
q    16
r    17
s    18
t    19
u    20
v    21
w    22
x    23
y    24
z    25
dtype: int64


# 12

In [7]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)

In [39]:
df = pd.DataFrame({'indice':ser.index,'numero':ser.values})

In [40]:
df

indice  numero
0       a       0
1       b       1
2       c       2
3       e       3
4       d       4
5       f       5
6       g       6
7       h       7
8       i       8
9       j       9
10      k      10
11      l      11
12      m      12
13      n      13
14      o      14
15      p      15
16      q      16
17      r      17
18      s      18
19      t      19
20      u      20
21      v      21
22      w      22
23      x      23
24      y      24
25      z      25

# 13

In [43]:
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))

In [50]:
df=pd.concat([ser1, ser2],axis=1)

In [51]:
df

0   1
0   a   0
1   b   1
2   c   2
3   e   3
4   d   4
5   f   5
6   g   6
7   h   7
8   i   8
9   j   9
10  k  10
11  l  11
12  m  12
13  n  13
14  o  14
15  p  15
16  q  16
17  r  17
18  s  18
19  t  19
20  u  20
21  v  21
22  w  22
23  x  23
24  y  24
25  z  25